name: Test PayID

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master


jobs:
  pay:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code  
      uses: actions/checkout@v2
  
    - name: get commit message
      run: |
        echo ::set-env name=commit_log::$(git log --format=%B ${{ github.event.before }}..${{ github.event.after }})

    - name: Run PayID
      uses: hammertoe/payid_xrp_action@33bd954
      with:
        wallet_secret: ${{ secrets.PAYID_WALLET_SECRET }}
        amount: 2002
        commit_log: ${{ env.commit_log }}
