name: Pay on test coverage improvement

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master


jobs:
  pay:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout prior code  
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.before }}
        path: .old-code

    - name: Checkout current code  
      uses: actions/checkout@v2
      with:
        path: .new-code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install old code dependencies
      run: |
        cd .old-code
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests on old code
      run: |
        cd .old-code
        pytest --cov-report=xml --cov tests/
        python -c "import xml.etree.ElementTree as ET; print('::set-env name=old_coverage::', ET.parse('coverage.xml').getroot().attrib['line-rate'])"

    - name: Install new code dependencies
      run: |
        cd .new-code
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run test on new code
      run: |
        cd .new-code
        pytest --cov-report=xml --cov tests/
        python -c "import xml.etree.ElementTree as ET; print('::set-env name=new_coverage::', ET.parse('coverage.xml').getroot().attrib['line-rate'])"

    - name: Run PayID
      uses: hammertoe/payid_xrp_action@2.0
      if: ${{ env.new_coverage > env.old_coverage }}
      with:
        wallet_secret: ${{ secrets.PAYID_WALLET_SECRET }}
        amount: ${{ (env.new_coverage - env.old_coverage) * 100 }}
        commit_log: ${{ env.commit_log }}