name: Test PayID

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master


jobs:
  pay:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code  
      uses: actions/checkout@v2
      with:
        fetch-depth: 5

    - name: Checkout prior code  
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.before }}
        path: .old-code

    - name: Checkout current code  
      uses: actions/checkout@v2
      with:
        path: .new-code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run PayID
      uses: hammertoe/payid_xrp_action@d78333e
      with:
        wallet_secret: ${{ secrets.PAYID_WALLET_SECRET }}
        amount: 2001
        commit_log: ${{ env.commit_log }}
