name: PayID PR Coverage Action

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened, closed]

jobs:
  pay:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install testing
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov

    - name: Checkout prior code  
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.base.sha }}
        path: .old-code

    - name: Install old code dependencies
      run: |
        cd .old-code
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        cd ..

    - name: Run tests on old code
      run: |
        cd .old-code
        pytest --cov-report=xml --cov=foo test.py
        cd ..

    - name: Checkout current code  
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        path: .new-code

    - name: Install new code dependencies
      run: |
        cd .new-code
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        cd ..

    - name: Run test on new code
      run: |
        cd .new-code
        pytest --cov-report=xml --cov=foo test.py
        cd ..

    - name: Run PayID
      uses: hammertoe/payid_xrp_pr_coverage_action@master
      with:
        repo_token: ${{secrets.GITHUB_TOKEN}}
        wallet_secret: ${{ secrets.PAYID_WALLET_SECRET }}
        old_coverage_file: /home/runner/work/test_repo/test_repo/.old-code/coverage.xml
        new_coverage_file: /home/runner/work/test_repo/test_repo/.new-code/coverage.xml
